source $HOME/.config/nvim/plug-config/essential.vim
source $HOME/.config/nvim/plug-config/plug.vim
source $HOME/.config/nvim/plug-config/rainbow.vim
source $HOME/.config/nvim/plug-config/lightline.vim
source $HOME/.config/nvim/plug-config/onehalf.vim
source $HOME/.config/nvim/plug-config/coc-extensions.vim
source $HOME/.config/nvim/plug-config/coc.vim
source $HOME/.config/nvim/plug-config/sneak.vim
source $HOME/.config/nvim/plug-config/vim-which-key.vim
luafile $HOME/.config/nvim/plug-config/vim-treesitter.lua
source $HOME/.config/nvim/plug-config/fzf.vim
source $HOME/.config/nvim/plug-config/vimspector.vim
source $HOME/.config/nvim/plug-config/asyncrun.vim
source $HOME/.config/nvim/plug-config/accelerated-jk.vim
