source $HOME/.config/nvim/plug-config/essential.vim
source $HOME/.config/nvim/plug-config/plug.vim
luafile $HOME/.config/nvim/plug-config/vim-treesitter.lua
source $HOME/.config/nvim/plug-config/coc-extensions.vim
source $HOME/.config/nvim/plug-config/coc.vim
source $HOME/.config/nvim/plug-config/lightline.vim
source $HOME/.config/nvim/plug-config/onehalf.vim
source $HOME/.config/nvim/plug-config/sneak.vim
source $HOME/.config/nvim/plug-config/vim-which-key.vim
source $HOME/.config/nvim/plug-config/vimspector.vim
source $HOME/.config/nvim/plug-config/asyncrun.vim
source $HOME/.config/nvim/plug-config/accelerated-jk.vim
source $HOME/.config/nvim/plug-config/asynctask.vim
source $HOME/.config/nvim/plug-config/nord.vim
source $HOME/.config/nvim/plug-config/fzf.vim
source $HOME/.config/nvim/plug-config/spelunker.vim
luafile $HOME/.config/nvim/plug-config/nvim-colorizer.lua
