let g:coc_global_extensions = [
      \'coc-yaml', 
      \'coc-vimlsp',
      \'coc-tsserver',
      \'coc-toml',
      \'coc-snippets',
      \'coc-rust-analyzer',
      \'coc-python',
      \'coc-json',
      \'coc-html',
      \'coc-go',
      \'coc-explorer',
      \'coc-css',
      \'coc-git',
      \]
